# MerMer Default Config

title = "MerMer"

[base]
folder = "MerMer-framework"
static = "./build/"
debug = false
serviceUserID = "lotto"
servicePassword = "P@ssw0rd"

[socket]
socket_host = "http://127.0.0.1"

[blockchain]
type = "ethereum"
watchWallet = "0xacE258f5F6AB1fa6f5730Df066f8514976081850"
twx_contract = ""

[database]
protocol = "mongodb"
db = "//localhost:27017/lotto"
user = ""
password = ""
dbName = "lotto"

[infura]
id = ""
secret = ""
endpoint = ""

[mailer]
host = 'smtp.gmail.com'
secure = true
port = 465
user = ''
password = ''

[microservice]
keychain = "http://127.0.0.1:5566"
keystone = "http://127.0.0.1:5999"
trust = "http://127.0.0.1:5567"
currency = "http://127.0.0.1:3333"

[api]
pathname = [
  "get | /,/version | Static.Utils.readPackageInfo",
  "get | /check | Bot.User.CheckPagePool",

  # lotto
  "post | /lotto/:userID | Bot.Lotto.BuyLottoTicket",
  # "get | /lotto | Bot.Lotto.GetLottoNumber",
  "get | /lotto/:id | Bot.Lotto.GetLottoTicket",
  "get | /drawn/:id | Bot.Lotto.DrawnLottoTicket",
  "get | /lottoIssue | Bot.Lotto.GetLottoIssue",

  # user
  "post | /user/register | Bot.User.Register",
  "get | /user/:userID/info | Bot.User.GetUserInfo",
  "get | /user/:userID/email | Bot.User.SendKeyToEmail"
]